"""initial schema

Revision ID: 7fd62e721315
Revises: 
Create Date: 2026-05-03 16:22:50.661602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd62e721315'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('campus_location', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', name='user_role', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_number', sa.String(length=32), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.SmallInteger(), nullable=True),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_roll_number'), ['roll_number'], unique=True)

    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=32), nullable=False),
    sa.Column('designation', sa.String(length=80), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teachers_employee_code'), ['employee_code'], unique=True)

    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_courses_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('active', 'dropped', name='enrollment_status', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_enrollments_student_course')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_student_id'), ['student_id'], unique=False)

    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('start_window', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_window', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_course_id'), ['course_id'], unique=False)

    op.create_table('exam_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pre_check', 'in_progress', 'submitted', 'expired', 'aborted_vm', 'aborted_stealth_vm', name='session_status', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_sessions_status'), ['status'], unique=False)
        batch_op.create_index('ix_exam_sessions_student_exam', ['student_id', 'exam_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=4000), nullable=False),
    sa.Column('question_type', sa.Enum('mcq', 'short_answer', name='question_type', native_enum=False), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('option_a', sa.String(length=500), nullable=True),
    sa.Column('option_b', sa.String(length=500), nullable=True),
    sa.Column('option_c', sa.String(length=500), nullable=True),
    sa.Column('option_d', sa.String(length=500), nullable=True),
    sa.Column('correct_option', sa.Enum('A', 'B', 'C', 'D', name='correct_option', native_enum=False), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.CheckConstraint('marks > 0', name='ck_questions_marks_positive'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_exam_id'), ['exam_id'], unique=False)

    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(length=8000), nullable=True),
    sa.Column('marks_awarded', sa.Float(), nullable=True),
    sa.Column('is_auto_graded', sa.Boolean(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_answers_session_question')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_session_id'), ['session_id'], unique=False)

    op.create_table('incident_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('incident_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='incident_severity', native_enum=False), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('cpu_thermal_value', sa.Float(), nullable=True),
    sa.Column('timing_latency_ms', sa.Float(), nullable=True),
    sa.Column('evidence_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_logs_incident_type'), ['incident_type'], unique=False)
        batch_op.create_index('ix_incident_logs_session_occurred', ['session_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_logs_severity'), ['severity'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_logs_severity'))
        batch_op.drop_index('ix_incident_logs_session_occurred')
        batch_op.drop_index(batch_op.f('ix_incident_logs_incident_type'))

    op.drop_table('incident_logs')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_session_id'))
        batch_op.drop_index(batch_op.f('ix_answers_question_id'))

    op.drop_table('answers')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_exam_id'))

    op.drop_table('questions')
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_exam_sessions_student_exam')
        batch_op.drop_index(batch_op.f('ix_exam_sessions_status'))

    op.drop_table('exam_sessions')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_course_id'))

    op.drop_table('exams')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_student_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_course_id'))

    op.drop_table('enrollments')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_courses_code'))

    op.drop_table('courses')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_employee_code'))
        batch_op.drop_index(batch_op.f('ix_teachers_department_id'))

    op.drop_table('teachers')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_roll_number'))
        batch_op.drop_index(batch_op.f('ix_students_department_id'))

    op.drop_table('students')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    # ### end Alembic commands ###
